apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
        - name: django-web
          image: django_app
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config

          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: ClusterIP
  selector:
    app: django-web
  ports:
    - name: django-web
      protocol: TCP
      port: 80
      targetPort: 80
