apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cronjob
  labels:
    app.kubernetes.io/name: django-app
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django-app
        spec:
          containers:
            - name: clearsessions-container
              image: django_app
              imagePullPolicy: Never
              command:
                - python
                - manage.py
                - clearsessions
              envFrom:
                - configMapRef:
                    name: app-config
          restartPolicy: Never
