apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  activeDeadlineSeconds: 40
  ttlSecondsAfterFinished: 50
  template:
    spec:
      containers:
        - name: migrate-container
          image: django_app
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
          command: ["python", "manage.py", "migrate", "--noinput"]
      restartPolicy: Never
