apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app.kubernetes.io/name: django-deployment
    app.kubernetes.io/component: django-migrate

spec:
  activeDeadlineSeconds: 40
  ttlSecondsAfterFinished: 50
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-deployment
        app.kubernetes.io/component: django-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: django-migrate
          image: seregaz1985/django_app
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: app-config
