version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

    env_file:
      - .env

    ports:
      - 5432:5432

  web:
    build: backend_main_django
    image: django_app
    volumes:
      - ./backend_main_django:/code
    env_file:
      - .env

    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db

volumes:
  db_data:
